url: http://essentialjs.com
img_url: http://essentialjs.com/images
title: Essential JavaScript
description: Just the essentials for a great web application.
email: henrik@thepia.com
analytics_id: UA-22749258-1

exclude: _design, README.textile, demo, Rakefile
destination: _site
lsi: false
pygments: true
markdown: maruku
permalink: pretty
maruku:
  use_tex: false
  use_divs: false
  png_dir: images/latex
  png_url: /images/latex
